package actions;

import dao.Dao;
import formbeans.AddUserForm;
import model.User;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Created by korenev on 19.04.2016.
 */
public class AddUserAction extends Action {
    @Override
    public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) throws Exception {
        AddUserForm addUserForm = (AddUserForm)form;

        User user = new User();
        user.setUserName(addUserForm.getName());
        user.setUserSurname(addUserForm.getSurname());
        user.setEmail(addUserForm.getEmail());
        user.setAdmin(addUserForm.isAdmin());

        //save user and return id generated by DB
        int id = new Dao().createUser(user);

        request.setAttribute("id",id);
        return mapping.findForward("success");
    }
}
